/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calls' | '/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/vehicles/$id'
  id: '__root__' | '/' | '/calls' | '/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  VehiclesIdRoute: VehiclesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
